name: Publish Timestamped Release

on: [workflow_dispatch]

jobs:
  publish-to-dev-ballerina-central:
    name: Publish Timestamped Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ballerina-platform'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Change to Timestamped Version
        run: |
          startTime=$(TZ="Asia/Kolkata" date +'%Y%m%d-%H%M00')
          latestCommit=$(git log -n 1 --pretty=format:"%h")
          VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)
          updatedVersion=${VERSION}-${startTime}-${latestCommit}
          echo "Updated Version: ${updatedVersion}"
          sed -i "s/version=\(.*\)/version=${updatedVersion}/g" gradle.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish artifact
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
          BALLERINA_DEV_CENTRAL: true
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          packagePublishRepo: ${{ github.repository }}
        run: |
          ./gradlew clean build publish --scan
